services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://postgres:postgres@postgresql:5432/english_learning
    restart: always
  postgresql:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "english_learning"
      POSTGRES_HOST_AUTH_METHOD: "trust"
