name: Build and Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'

      - name: Install dependencies
        run: |
          go mod download

      - name: Run build
        run: make build-linux

      - name: Run testing
        run: go test -v ./...

      - name: Package artifacts
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          mkdir -p package
          cp ./bin/enblish-learning-bot ./package/english-learning-bot
          cp ./bin/english-learning-api ./package/english-learning-api
          cp -r ./web/dist ./package/web
          cd package
          zip -r ../english-learning-release.zip .
          cd ..

      - name: Upload artifacts
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: actions/upload-artifact@v4
        with:
          name: english-learning-release
          path: english-learning-release.zip
          retention-days: 30