name: web-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read


jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type checking
        run: npm run typecheck
        if: ${{ hashFiles('./web/package.json') != '' && contains(hashFiles('./web/package.json'), 'typecheck') }}